[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
HCubature = "19dc6840-f33b-545b-b366-655c7e3ffd49"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
LazySets = "b4f0291d-fe17-52bc-9479-3d1a343d9043"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Plotly = "58dd65bb-95f3-509e-9936-c39a10fdeae7"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SymPy = "24249f21-da20-56a4-8eb1-6a02cf4ae2e6"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
